### ISSUE TITLE
Spec that passed with Poltergeist fails without sleep to ensure JS runs first

### ISSUE THREAD

**Issue by henrik** [twalpole/apparition#32]
We've got a Capybara spec that essentially does

```
visit my_path
click_link "Add the thing"
fill_in "the_thing"
```

We've got JavaScript like

```
$(function() {
  $(".add-the-thing").on("click", append_the_thing_to_the_page);
});
```

This test runs fine on Poltergeist, but with Apparition it fails unless we add e.g. `sleep 0.1` like so:

```
visit my_path
click_link "Add the thing"
sleep 0.1
fill_in "the_thing"
```

After some `console.log`ing, it seems that Apparition runs the `fill_in` too soon – before the on click event has been attached.

Even if Apparition retries the fill_in, that won't help, because the problem is the click.

We could (and probably will) work around it by not showing the link until the JS event has been loaded or something similar (maybe waiting for some selector to be added to body), but I still thought I'd report this as one possible issue if the lib aims to be as close as possible to a drop-in replacement for Poltergeist.

If you've got any better ideas for how to solve or work around it, we'd love to hear them :)

This is quite a big project, so maybe pages and JS takes longer to load than it would in a minimal project. We haven't tried reproducing it in a small project and probably won't if we can work around it :/

**Comment by henrik** [comment]
This is slightly better than the sleep, but not great:

```
Timeout.timeout(Capybara.default_max_wait_time) do
 loop do
   jsHasLoaded = page.evaluate_script("!!window.jQuery")
   break if jsHasLoaded
 end

**Comment by henrik** [comment]
Now doing this:

```
<a href="#" class="add-the-thing" style="display: none;">Add the thing</a>
```

and

```
$(function() {
  $(".add-the-thing").show().on("click", append_the_thing_to_the_page);
});
```

Now we can lean on Capybara's retries, and it will also avoid any real world issues where a user tries to click it too soon.

**Comment by twalpole** [comment]
You shouldn't be waiting for js to load, you should be waiting for whatever page element changes that js being loaded creates. If there aren't detectable changes (enabling buttons, adding elements, etc) then the page is already buggy if a user clicks things before the JS runs.

**Comment by henrik** [comment]
Yeah, we came to realise the same. It's a bit trickier with the Rails built-in UJS stuff. E.g. with `link_to("Text", url, method: "post")` we'd need to add further JS to hide the link until Rails enhances it, or something like that.

In practical terms, our JS loads fast enough in prod that this hasn't been a real-world issue AFAIK, but something about how it loads and runs in Apparition makes it an issue there. We didn't have this issue with PhantomJS and I don't believe we had it with our Selenium+ChromeDriver explorations. Just wondering if there's some difference between Apparition and PhantomJS/Selenium that would explain this and if so, if it could make any sense to try to change it.

But I can definitely see the case for not considering it Apparition's problem, as it were :)

**Comment by twalpole** [comment]
Really the only thing that's different would be the speed that different things run at.

**Comment by henrik** [comment]
Alright, no worries. Will close the ticket. If we make any new discoveries we'll write them here :)

**Comment by lawso017** [comment]
@twalpole thanks for this fantastic library. Working on a Rails 4 -> 5 upgrade and moving to Apparition from capybara-webkit; we have run into a similar version of this same problem. In our case we're simply loading a page and then calling page.executeScript with a bit of jQuery. However unlike capybara-webkit we are having to manually sleep until jQuery loads otherwise we generate Capybara::Apparition::JavascriptError ReferenceError: $ is not defined.

I think I'm missing something obvious since this is such a basic use case and capybara-webkit (and capybara) handled this situation seamlessly for years. There's no visual indication that the application.js (and jQuery) in our page has loaded, of course, and sleeping everywhere is suboptimal. 

Any suggestions greatly appreciated. Will explore the code and see if I'm missing something.

**Comment by henrik** [comment]
@lawso017 We've seen those also. IIRC we’ve sprinkled our wait_for_js_to_load various places (often as the very last line of a test, I think?) to work around them. Godspeed on your explorations :)

**Comment by twalpole** [comment]
@lawso017 What is the JS you're trying to execute actually doing?  Using execute_script is generally not a great thing since your users would never be interacting with the page like that.  If you really do need to use execute_script, one option would be to only use standard JS rather than jQuery in any scripts you're writing - another would be to use `execute_async_script` and write your script so that it checks if JQuery is loaded yet, and if not sleeps for a bit and tries again.

**Comment by lawso017** [comment]
@twalpole we have some helper functions that use `execute_script` to trigger UI interactions that were easier to manipulate via controls' Javascript APIs than mouse clicks and keyboard input. You're right that users do not interact via the page like that; however in some cases we opt for test simplicity when the goal is not to test the UI/UX of a JS control but rather to get the form into a specific state.

Having said that, I've been trying to generate some suitable debug output to compare the CDP messages between Apparition and Cuprite. So far, however, I've been stymied by the following error when I attempt to run specs via the command line with a DEBUG environment variable:

```
DEBUG=true ./bin/rspec spec/features/employee_portal/user_profile_spec.rb:15
Running via Spring preloader in process 62697
Run options: include {:focus=>true, :locations=>{"./spec/features/employee_portal/user_profile_spec.rb"=>[15]}}

Randomized with seed 38862

employees
Capybara starting Puma...
* Version 4.3.1 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:49619
{}
{"browserContextId"=>"ED8520F6E23E2457FC759A0EF3FCE15C"}
{"sessionId"=>"CD9D53D626C259B2672A3636EE2846C5"}
Setting loading to -1
Setting loaded - was -1
Unexpected inner loop exception: undefined local variable or method `params' for #<Capybara::Apparition::Page:0x00007fbf6b03a430>: undefined local variable or method `params' for #<Capybara::Apparition::Page:0x00007fbf6b03a430>: 
["/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/page.rb:512:in `block in register_event_handlers'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:211:in `block in process_handlers'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `each'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:207:in `process_handlers'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:185:in `block in process_messages'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `loop'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:175:in `process_messages'", "/Users/williamlawson/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/apparition-0.4.0/lib/capybara/apparition/driver/chrome_client.rb:217:in `block in start_threads'"]
Timedout waiting for reset
  user updates profile (FAILED - 1)
```

... incidentally, I have found that the only way I can generate _any_ debug output is via a DEBUG environment variable. Startup options like:

`Capybara::Apparition::Driver.new(app, debug: true, logger: STDOUT, browser_logger: STDOUT, headless: true)`

... appear to have no effect.

Having said that, our test suite is running without errors using Cuprite and at this point I'd consider Cuprite a drop-in replacement for capybara-webkit. Looking at the Cuprite debug logs, it appears that Cuprite / Ferrum are waiting for several key events before beginning (or continuing) to interact with the page. 

For example, Cuprite will initiate a navigation request with the following message:

```
▶ 0.2790999999269843 {"method":"Page.navigate","params":{"url":"http://127.0.0.1:49247/?as=7866"},"id":1012}
```

It then waits as the request is processed, receiving a ton of messages in response, and does not send another message until the following messages are received:

```
    ◀ 3.445291999960318 {"method":"Page.navigatedWithinDocument","params":{"frameId":"C18EC0D7675CEA5E94B8F83BFCA331F0","url":"http://127.0.0.1:49247/?as=7866"}}
    ◀ 3.4454950001090765 {"method":"Page.loadEventFired","params":{"timestamp":799214.986819}}
    ◀ 3.4455420000012964 {"method":"Page.frameStoppedLoading","params":{"frameId":"C18EC0D7675CEA5E94B8F83BFCA331F0"}}
    ◀ 3.4455929999239743 {"method":"DOM.documentUpdated","params":{}}
    ◀ 3.4456529999151826 {"method":"Page.domContentEventFired","params":{"timestamp":799214.987492}}
```
in another example, the below sequence is observed:
```
    ◀ 4.075126999989152 {"method":"Network.dataReceived","params":{"requestId":"61106.105","timestamp":799215.617089,"dataLength":4458,"encodedDataLength":0}}
    ◀ 4.075180999934673 {"method":"Network.loadingFinished","params":{"requestId":"61106.105","timestamp":799215.616849,"encodedDataLength":507,"shouldReportCorbBlocking":false}}
    ◀ 4.0758269999641925 {"method":"Page.loadEventFired","params":{"timestamp":799215.617713}}
    ◀ 4.075878000119701 {"method":"Page.frameStoppedLoading","params":{"frameId":"C18EC0D7675CEA5E94B8F83BFCA331F0"}}
```

... it seems that loadEventFired and frameStoppedLoading are common denominators in terms of Cuprite's awaiting a signal to move forward.

Am curious to continue looking into this and appreciates @henrik 's insight as well -- I am mostly motivated by a desire to speed things up because our test suite run time has doubled at this point from 20min to 40min moving from Rails 4.2 to 5.0 / capybara-webkit to Cuprite -- including using a whitelist to eliminate all non-essential network activity. I can understand some increase having seen how chatty the CDP protocol is... but am hoping to do better than 40 minutes :-).

**Comment by henrik** [comment]
In case it helps others, we had a problematic smoke test where waiting for jQuery to load wasn't enough; we ended up waiting for `page.evaluate_script("document.readyState === 'complete'")`, and also had to wait a bit longer than the Capybara default wait time.

To be clear, I don't consider this an elegant solution, but until we figure out something better it's what we're doing.

We also discussed this situation a bit at work since a team was bitten quite hard (as in spent a lot of time) by these differences to Poltergeist. @twalpole, not sure about how feasible it is, but would you be open to a setting (maybe as a PR, if we could figure it out) where Apparition can be configured to wait similar to what Poltergeist did and what Cuprite seems to do as well?

So the user would have a choice between "it behaves more like a real browser, where assertions can theoretically run before everything is loaded" and "it's less realistic but is more like Poltergeist in avoiding a common (?) gotcha".

**Comment by twalpole** [comment]
Sure
